### ISSUE TITLE
Inference example does not show results

### ISSUE THREAD

**Issue by HripsimeS** [ruhyadi/YOLO3D#11]
@ruhyadi Hello!

I tried to run your inference example on Google Colab, but unfortunatly the last cell did not show any 3D object detection.
Please find the notebook in this link https://github.com/HripsimeS/Projects/blob/main/YOLO3D_Inference.ipynb

Any ideas what is going on with the code? Thanks in advance!

Hripsime

**Comment by ruhyadi** [comment]
Hy @HripsimeS 
For quick answer, would you install all dependencies from requirements.txt. My current assumption is that the problem is with the version of pytorch you are using, please use **pytorch version 1.8.1** and **torchvision version 0.9.1**. [see this](https://pytorch.org/get-started/previous-versions/#v181). 
```
pip install torch==1.8.1 torchvision==0.9.1
```

By the way, I no longer maintain this repo, new implementation of YOLO3D (from [Deep3DBox](https://arxiv.org/abs/1612.00496)) you can see it at [ruhyadi/yolo3d-lightning](https://github.com/ruhyadi/yolo3d-lightning).

**Comment by HripsimeS** [comment]
@ruhyadi Thank you very much for your reply! I installed the following versions
conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge

But while running the cell for inference I received the following error "Torch not compiled with CUDA enabled".
It seems pytorch==1.8.1 torchvision==0.9.1 with cudatoolkit=11.3 is too old for my laptop, as only pytorch== 1.12.1 torchvision== 0.13.1 with cudatoolkit=11.6 is working well for me.

In order to keep the latest version of pytorch/torchvision and fix the AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor', I did the following:

I modifed the upsampling.py in \anaconda3\envs\envname\Lib\site-packages\torch\nn\modules (conda files) , according to the function below.

def forward(self, input: Tensor) -> Tensor:
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
                         #recompute_scale_factor=self.recompute_scale_factor
                         )

Now it works fine and I have a good 3D Bourding Box :)
https://github.com/HripsimeS/Projects/blob/main/YOLO3D_Inference.ipynb

**Comment by ruhyadi** [comment]
Wow that's great, nice to hear this things work. 
So, the problems is in PyTorch version in order to run YOLOv5.
I think PyTorch v1.8.1 should be install with cudatoolkit=10.1 like i did.
```
conda create -n yolo3d python=3.8 cudatoolkit=10.1
conda activate yolo3d
pip install torch==1.8.1 torchvision==0.9.1
```
But again, it's nice to see this things work.

Don't hesitate to push issue again, and please try [ruhyadi/yolo3d-lightning](https://github.com/ruhyadi/yolo3d-lightning) for better results.

Regards,

Didi
