### ISSUE TITLE
why orient_loss is always -0.99XXXXX, and it will never  go down？

### ISSUE THREAD

**Issue by mvpzhangqiu** [ruhyadi/YOLO3D#15]
I have this problem when I train my own dataset

**Comment by mvpzhangqiu** [comment]
![1679553839145](https://user-images.githubusercontent.com/14309504/227124338-2766de80-0e1e-4da1-a446-5ffade3e57c0.jpg)

**Comment by ruhyadi** [comment]
I am no longer doing maintenance on this repository, please train your model with new repo [yolo3d-lightning](https://github.com/ruhyadi/yolo3d-lightning).
As far as I understand the loss value is minus and this is normal, please visit the author's paper: https://arxiv.org/pdf/1612.00496.pdf.
Stopping the loss value from getting lower can be caused by many things, you can fix it by changing the backbone model (use Mobilenet, I get loss ~ - 1.5) or changing the optimizer.
