### ISSUE TITLE
FileNotFoundError !

### ISSUE THREAD

**Issue by devendraswamy** [ruhyadi/YOLO3D#7]
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/3d_det/ACP_3Detection/YOLO3D/dataset/KITTI/training/calib/', please anyone help me to debug , Thanking you in advance.

**Comment by ruhyadi** [comment]
I think you want to do model training. This my bad, not including dataset preparation in the readme. I will update the readme soon.
For now you can use my training [notebook on Kaggle](https://www.kaggle.com/code/didiruh/training-yolo) (because Kaggle already has the KITTI dataset). When training you may need an API KEY to log in to Comet.ml, get an API KEY by following the [following link](https://www.comet.ml).
Feel free to use.

**Comment by devendraswamy** [comment]
Thank you for your support , Could you please elaborate the details of Image_2,label_2,calib folders in kitti dataset ? Thanking you in advance

**Comment by ruhyadi** [comment]
As you can see on the [KITTI website](http://www.cvlibs.net/datasets/kitti/setup.php), there are 4 cameras used by KITTI, including two pairs of stereo cameras (color and gray). `image_2`, `label_2` are the images and annotations captured by the 2nd Camera (color) respectively. Meanwhile, `calib` is a folder containing the calibration matrix of all cameras and lidar. 
It should be emphasized again in this case that, YOLO3D is a method for monocular (single camera) 3D object detection. Thus, YOLO3D does not require data related to **Lidar** or **the first, third or fourth camera**, which is in the `image_1`, `image_3`, `image_4` folder and also any `label` folders that accompany it.

**Comment by devendraswamy** [comment]
Thank you so much , could you please suggest the any "labelling tool" supported to yolo3d detection ? Please help me.
